const Deck = require('./deck')

const myDeck = new Deck()
console.log('This is how the cards are represented:\n')
console.log(JSON.stringify(myDeck.cards))
console.log('After shuffling:\n')
myDeck.shuffle()
console.log(JSON.stringify(myDeck.cards))
console.log('After sorting:\n')
myDeck.sort()
console.log(JSON.stringify(myDeck.cards))
